In [5]:
import pandas as pd
import numpy as np

In [13]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv' # Raw CSV File Link

In [14]:
pd.read_csv(data) #Load the dataset

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [15]:
df = pd.read_csv(data) #Load the dataset and create data frame

In [16]:
len(df) # return the total number of records in the dataset

9704

In [17]:
pd.__version__

'2.2.3'

In [18]:
df.fuel_type

0       Gasoline
1       Gasoline
2       Gasoline
3         Diesel
4       Gasoline
          ...   
9699      Diesel
9700    Gasoline
9701      Diesel
9702      Diesel
9703      Diesel
Name: fuel_type, Length: 9704, dtype: object

In [19]:
num_fuel_types = df['fuel_type'].nunique() # Count unique fuel types

In [20]:
num_fuel_types

2

In [21]:
print(f"Number of unique fuel types : {num_fuel_types}")

Number of unique fuel types : 2


In [24]:
missing_values = df.isnull().sum() # This shows exactly how many missing values are in each column.

In [25]:
print(missing_values)

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64


In [26]:
max_fuel_efficiency = df['fuel_efficiency_mpg'].max()

In [27]:
max_fuel_efficiency

np.float64(25.96722204888372)

In [28]:
asia_cars = df[df['origin'] == 'Asia'] # Filter cars from Asia

In [29]:
max_fuel_efficiency = asia_cars['fuel_efficiency_mpg'].max()

In [30]:
print(f"Maximum Fuel Efficiency: {max_fuel_efficiency}")

Maximum Fuel Efficiency: 23.759122836520497


In [32]:
df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [46]:
median_hp = df['horsepower'].median() #selects the horsepower column and computes median value 

In [47]:
print(median_hp)

149.0


In [42]:
most_frequent_hp = df['horsepower'].mode()[0] #returns a series of the most frequent values in the horsepower column and selects the one that occurs the most

In [36]:
print("Most frequent Horsepower:", most_frequent_hp)

Most frequent Horsepower: 152.0


In [52]:
df['horsepower'] = df['horsepower'].fillna(most_frequent_hp) # Fill missing values with the most frequent value

In [53]:
print(df['horsepower'].isnull().sum()) # Verify there are no missing values left

0


In [54]:
df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0       152.0     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  Horsepower  
0           0.0            13.231729       159.0  
1           0.0            13.688217        97.0  
2           0.0            14.246341        78.0  
3           2.0            16.912736       152.0  
4           2.0            12.488369       140.0  
...         ...                  ...         ...  
9699        NaN            15.101802       164.0  
9700        0.0            17.962326       154.0  
9701       -1.0            17.186587       138.0  
9702        1.0            15.331551       177.0  
9703       -1.0            14.884467       140.0  

[9704 rows x 12 columns]

In [55]:
median_hp = df['horsepower'].median() #selects the horsepower column and computes median value 

In [56]:
print(median_hp)

152.0


In [59]:
asian_cars = df[df['origin'] == 'Asia'] # Filter rows where Region is 'Asia'

In [101]:
X = asian_cars[['vehicle_weight', 'model_year']] # Select only 'vehicle_weight' and 'model_year' columns

In [120]:
X = asian_cars_subset.head(7) 

In [121]:
X

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [122]:
X = X.to_numpy() # Convert to NumPy array

In [123]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [125]:
XT = X.T
XT

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [126]:
X.shape


(7, 2)

In [127]:
XT.shape


(2, 7)

In [136]:
XTX = np.dot(XT , X) # Compute matrix-matrix multiplication between the transpose of X and X.

In [129]:
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [137]:
XTX_inv = np.linalg.inv(XTX) # compute Invert XTX

In [131]:
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [132]:
XTX_inv.sum()

np.float64(1.562869705091685e-07)

In [133]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]

In [134]:
w = np.dot(np.dot(XTX_inv,XT),y) # Multiply the inverse of XTX with the transpose of X, and then multiply the result by y

In [135]:
w

array([0.01386421, 0.5049067 ])