In [1]:
import numpy as np

# Create Arrays

In [2]:
np.zeros(5) #creates an array of the specified size. Fills the array with zeros

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(5) #creates an array of the specified size. Fills the array with ones

array([1., 1., 1., 1., 1.])

In [4]:
np.full(5, 2.5) #creates an array of the specified size and number.

array([2.5, 2.5, 2.5, 2.5, 2.5])

In [14]:
[1,2,3,4,5]

[1, 2, 3, 4, 5]

In [5]:
np.array([1,2,3,4,5]) #Converts a python list to an array

array([1, 2, 3, 4, 5])

In [6]:
a = np.array([1,2,3,4,5]) #Converts a python list to an array

In [7]:
a

array([1, 2, 3, 4, 5])

In [8]:
a [2] # to access an element of the array

np.int64(3)

In [9]:
a [2] = 10 #replace the value in the array at that specific index

In [10]:
a

array([ 1,  2, 10,  4,  5])

In [11]:
np.arange(10) #creates a range of values based on the specified number

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(3,10) #creates a range of values based on the specified numbers

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(4,10) #creates a range of values based on the specified numbers

array([4, 5, 6, 7, 8, 9])

In [15]:
linspace_array = np.linspace(0, 1, 11)  # Creates 11 numbers from 0 to 1

In [16]:
linspace_array 

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [17]:
linspace_array = np.linspace(0, 100, 11)  # Creates 11 numbers from 0 to 1

In [18]:
linspace_array

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# Multi-dimensional Arrays

In [19]:
zeros_matrix = np.zeros((5, 2))
ones_matrix = np.ones((5, 2))
constant_matrix = np.full((5, 2), 3)

In [20]:
zeros_matrix

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [23]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
n[0,1]

np.int64(2)

In [25]:
n[0,1] = 20

In [26]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [27]:
n[0]

array([ 1, 20,  3])

In [28]:
n[:,2]

array([3, 6, 9])

In [29]:
n[0] = [1,1,1]

In [30]:
n

array([[1, 1, 1],
       [4, 5, 6],
       [7, 8, 9]])

# Randomly generated Arrays


In [37]:
np.random.seed(2)  # Set the seed, ensures random values are reproducible accross systems
random_array = np.random.rand(5, 2)  # Generates random numbers between 0 and 1

In [38]:
random_array 

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [39]:
np.random.seed(2)  # Set the seed, ensures random values are reproducible accross systems
random_array_n = np.random.randn(5, 2)  # Generates random numbers between 0 and 1 - get from normal distribution

In [40]:
random_array_n

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [41]:
np.random.seed(2)  # Set the seed, ensures random values are reproducible accross systems
normal_distribution = np.random.randn(5, 2)
random_integers = np.random.randint(low=0, high=100, size=(5, 2))

In [42]:
random_integers

array([[37, 39],
       [67,  4],
       [42, 51],
       [38, 33],
       [58, 67]])

# Element-wise Operations

In [43]:
a = np.arange(5)

In [44]:
a

array([0, 1, 2, 3, 4])

In [45]:
a /100

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [46]:
10 + (a/2)

array([10. , 10.5, 11. , 11.5, 12. ])

In [50]:
b = (10 + (a * 2)) ** 2 / 100

In [51]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

# Comparison Operations

In [52]:
a

array([0, 1, 2, 3, 4])

In [53]:
a >= 2

array([False, False,  True,  True,  True])

In [54]:
a > b

array([False, False,  True,  True,  True])

In [55]:
a[a>b]

array([2, 3, 4])

# Summarizing Operations

In [57]:
a.min()

np.int64(0)

In [58]:
a

array([0, 1, 2, 3, 4])

In [59]:
a.max()

np.int64(4)

In [61]:
a.mean()

np.float64(2.0)

In [62]:
a.std()

np.float64(1.4142135623730951)