In [2]:
import numpy as np

In [22]:
np.zeros(5) #creates an array of the specified size. Fills the array with zeros

array([0., 0., 0., 0., 0.])

In [23]:
np.ones(5) #creates an array of the specified size. Fills the array with ones

array([1., 1., 1., 1., 1.])

In [24]:
np.full(5, 2.5) #creates an array of the specified size and number.

array([2.5, 2.5, 2.5, 2.5, 2.5])

In [25]:
np.array([1,2,3,4,5]) #Converts a python list to an array

array([1, 2, 3, 4, 5])

In [26]:
a = np.array([1,2,3,4,5]) #Converts a python list to an array

In [27]:
a

array([1, 2, 3, 4, 5])

In [28]:
a [2] # to access an element of the array

np.int64(3)

In [29]:
a [2] = 10 #replace the value in the array at that specific index

In [30]:
a

array([ 1,  2, 10,  4,  5])

In [31]:
np.arange(10) #creates a range of values based on the specified number

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(3,10) #creates a range of values based on the specified numbers

array([3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(4,10) #creates a range of values based on the specified numbers

array([4, 5, 6, 7, 8, 9])