# Vector operations

In [13]:
import pandas as pd
import numpy as np

In [14]:
u = np.array([2, 4, 5, 6])
v = np.array([1, 0, 0, 2])

In [15]:
u + v # addition 

array([3, 4, 5, 8])

In [16]:
u - v # subtraction 

array([1, 4, 5, 4])

In [17]:
2 * v # scalar multiplication 

array([2, 0, 0, 4])

# Vector-vector multiplication

In [18]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [19]:
vector_vector_multiplication(u, v)

np.float64(14.0)

In [20]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1],
])

# Matrix-vector multiplication


In [21]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [22]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [23]:
U.dot(v)

array([14,  5,  5])

# Matrix-matrix multiplication


In [24]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0],
])

In [25]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [26]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

# Identity matrix

In [29]:
I = np.eye(3)

In [30]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
I = np.eye(3)

In [55]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
])

In [57]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [58]:
inv = np.linalg.inv(V)

In [59]:
inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])